name: GitHub Actions Demo for VulnNodeApp
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: build-and-deploy-app
    steps:
      - name: first-step
        run: ssh 
